// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCof5LEo7w2Rg9UU4A3trtB1IUfCdXQ7ak',
    appId: '1:815285463597:web:c4322462b8f2e08faf66a4',
    messagingSenderId: '815285463597',
    projectId: 'ai-life-organizer-65f37',
    authDomain: 'ai-life-organizer-65f37.firebaseapp.com',
    storageBucket: 'ai-life-organizer-65f37.firebasestorage.app',
    measurementId: 'G-99VYKBZ622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWGqVzv8qEKeBDZaGzXNyfp_7bxWCtr8U',
    appId: '1:815285463597:android:28a2dde2b23865e8af66a4',
    messagingSenderId: '815285463597',
    projectId: 'ai-life-organizer-65f37',
    storageBucket: 'ai-life-organizer-65f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVIVTm59WokOQuW6XOrML5FSG8uTv3hpY',
    appId: '1:815285463597:ios:8e7fb3e159b6bf12af66a4',
    messagingSenderId: '815285463597',
    projectId: 'ai-life-organizer-65f37',
    storageBucket: 'ai-life-organizer-65f37.firebasestorage.app',
    iosBundleId: 'com.ailife.aiLifeOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVIVTm59WokOQuW6XOrML5FSG8uTv3hpY',
    appId: '1:815285463597:ios:8e7fb3e159b6bf12af66a4',
    messagingSenderId: '815285463597',
    projectId: 'ai-life-organizer-65f37',
    storageBucket: 'ai-life-organizer-65f37.firebasestorage.app',
    iosBundleId: 'com.ailife.aiLifeOrganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCof5LEo7w2Rg9UU4A3trtB1IUfCdXQ7ak',
    appId: '1:815285463597:web:15cf643bd246aaabaf66a4',
    messagingSenderId: '815285463597',
    projectId: 'ai-life-organizer-65f37',
    authDomain: 'ai-life-organizer-65f37.firebaseapp.com',
    storageBucket: 'ai-life-organizer-65f37.firebasestorage.app',
    measurementId: 'G-EX4XS3YJ7S',
  );
}
