import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

import 'package:ai_life_organizer/core/theme/app_theme.dart';
import 'package:ai_life_organizer/router/app_router.dart';
import 'firebase_options.dart'; // <-- IMPORTANT (generated by FlutterFire)

/// Main entry point with Firebase initialization and error handling.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Global Flutter error handler
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.presentError(details);
    debugPrint("Flutter Error: ${details.exception}");
    debugPrint("Stack: ${details.stack}");
  };

  // Initialize Firebase safely
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint("🔥 Firebase initialized successfully");
  } catch (e, s) {
    debugPrint("❌ Firebase init error: $e");
    debugPrint("Stack: $s");
  } 

  runApp(
    const ProviderScope(
      child: AiLifeOrganizerApp(),
    ),
  );
}

/// Root app widget
class AiLifeOrganizerApp extends ConsumerWidget {
  const AiLifeOrganizerApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(goRouterProvider);

    return MaterialApp.router(
      title: 'AI Life Organizer',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      routerConfig: router,
    );
  }
}