/// A single task generated by the AI service (from JSON).
/// Plain class to avoid Freezed/JSON codegen conflict with custom fromJson.
class GeneratedTask {
  const GeneratedTask({
    required this.title,
    this.order = 0,
  });

  final String title;
  final int order;

  factory GeneratedTask.fromJson(Map<String, dynamic> json) {
    return GeneratedTask(
      title: json['title'] as String? ?? '',
      order: (json['order'] as num?)?.toInt() ?? 0,
    );
  }
}
